---
apiVersion: v1
kind: Service
metadata:
  name: dns-server
  labels:
    app: dns-server
spec:
  type: LoadBalancer
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
  selector:
    app: dns-server
