---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-lb-kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-ingress-nginx
rules:
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: list-ingress-nginx-to-sa
subjects:
  - kind: ServiceAccount
    name: nginx-lb-kubectl
roleRef:
  kind: Role
  name: list-ingress-nginx
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-load-balancer-deployment
spec:
  selector:
    matchLabels:
      app: nginx-load-balancer
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-load-balancer
    spec:
      serviceAccountName: nginx-lb-kubectl
      containers:
      - name: nginx
        imagePullPolicy: Always
        image: bharamicrosystems/nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
  labels:
    app: nginx-load-balancer
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-load-balancer
